CREATE TABLE IF NOT EXISTS `register` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_fname` varchar(255) NULL,
  `user_lname` varchar(255) NULL,
  `userfullname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `address_line_1` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `address_line_2` varchar(200) DEFAULT NULL,
  `phone_number` int NOT NULL,
  `user_image` varchar(255) NOT NULL,
  `user_birthdate` date DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `user_type` tinyint(1) DEFAULT '1',
  `user_role` tinyint(1) DEFAULT '1',
  `send_email` tinyint(1) DEFAULT '1',
  `password_reset_token` varchar(255) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `created_by` smallint DEFAULT NULL,
  `modified_on` datetime NOT NULL,
  `modified_by` smallint NOT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_by` smallint NOT NULL,
  `deleted_at` timestamp NOT NULL,
  PRIMARY KEY (`id`)
)